### ISSUE TITLE
在线代理域名池

### ISSUE THREAD

**Issue by qianlun502** [cmliu/WorkerVless2sub#12]
作者你好，代码里面有个在线代理域名池，我看到生成的节点全都使用的上面的伪装域名，这是为什么？麻烦作者大大帮我解惑

**Comment by cmliu** [comment]
> 作者你好，代码里面有个在线代理域名池，我看到生成的节点全都使用的上面的伪装域名，这是为什么？麻烦作者大大帮我解惑

因为你用的域名是workers或者pages分配的域名，这些域名已经被墙了，直接用是用不了的，所以我就给你套了代理域名去中转你被墙的域名
