### ISSUE TITLE
这个 API 提供了什么服务

### ISSUE THREAD

**Issue by jeffery9** [cmliu/WorkerVless2sub#14]
这个 API 做什么？ 代码库在哪

https://github.com/cmliu/WorkerVless2sub/blob/0e14fb553650c68920f34da8cbc540a01d6594d9/_worker.js#L202

**Comment by cmliu** [comment]
> 这个 API 做什么？ 代码库在哪
> 
> https://github.com/cmliu/WorkerVless2sub/blob/0e14fb553650c68920f34da8cbc540a01d6594d9/_worker.js#L202

https://github.com/cmliu/HY2sub
订阅的时候带上?sos才会启用, 属于应急的时候的备用节点, 但是节点出处不干净, 所以我才没在项目说明里提这事, 算是留给能看懂代码的人的彩蛋
