### ISSUE TITLE
往 TG 发送了什么

### ISSUE THREAD

**Issue by jeffery9** [cmliu/WorkerVless2sub#15]
https://github.com/cmliu/WorkerVless2sub/blob/d9432c7744f3be9ad6238c8a67144c2be51e380b/_worker.js#L217

**Comment by cmliu** [comment]
> https://github.com/cmliu/WorkerVless2sub/blob/d9432c7744f3be9ad6238c8a67144c2be51e380b/_worker.js#L217

推荐查看我制作的视频内容
