### ISSUE TITLE
肥羊的代码在哪里可以获取

### ISSUE THREAD

**Issue by jeffery9** [cmliu/WorkerVless2sub#16]
https://github.com/cmliu/WorkerVless2sub/blob/d9432c7744f3be9ad6238c8a67144c2be51e380b/_worker.js#L22

**Comment by cmliu** [comment]
这个你可以添加肥羊的TG群去问他比较合适

**Comment by jeffery9** [comment]
不知道他的 TG 是什么
你的 TG 好像只能看，不能发言
