### ISSUE TITLE
能否为SSR生成配置订阅地址？

### ISSUE THREAD

**Issue by marslulu** [cmliu/WorkerVless2sub#29]
类似给clash的订阅配置一样，能否在SSR上实现？https://sub.cmliussss.workers.dev/auto?format=clash
俺是小白，可能问的小白了一些，不好意思。
我让ssr去按照这个地址订阅，导不出任何节点：https://sub.cmliussss.workers.dev/auto

**Comment by cmliu** [comment]
导不出节点的原因是因为ssr不支持vless, 你应该去找ssr来支持vless节点
