### ISSUE TITLE
Error1101

### ISSUE THREAD

**Issue by guanghei** [cmliu/WorkerVless2sub#37]
CM老师，2024.5.16布置优选订阅生成器同样出现1101error，本来想进telegram群问问，结果没发一句话就被踢出来拉黑了，我telegram的ID是@heiguangbl

**Comment by cmliu** [comment]
> CM老师，2024.5.16布置优选订阅生成器同样出现1101error，本来想进telegram群问问，结果没发一句话就被踢出来拉黑了，我telegram的ID是@heiguangbl

解了
