### ISSUE TITLE
clash 订阅如何取消分组

### ISSUE THREAD

**Issue by xlc520** [cmliu/WorkerVless2sub#53]
使用clash订阅如何取消分组，不要分美国、日本什么的，直接像普通的配置一样，在节点选择显示所有的节点，因为有时候更新订阅之后有些分组没有节点，只有 一个direct，direct测试延迟比较低，就会选择这些 只有 一个direct的组，导致无法使用代理节点。

![image](https://github.com/cmliu/WorkerVless2sub/assets/56480807/7ea868a8-be86-4827-bc94-c6d2ef595ee3)

![image](https://github.com/cmliu/WorkerVless2sub/assets/56480807/998f6c69-9484-45c1-a43c-69ac47a10fac)

**Comment by cmliu** [comment]
自行添加变量SUBCONFIG
