### ISSUE TITLE
请问能加个 `&format=` 用于不用客户端的订阅吗？

### ISSUE THREAD

**Issue by fscarmen** [cmliu/WorkerVless2sub#6]
样例
```
https://sub.xf.free.hr/api/sub?host=ed.ariesver.online&uuid=73b6dbd5-a27a-4c76-9ad1-42a82380dddb&path=/?ed=2048&format=base64
```
```
https://sub.xf.free.hr/api/sub?host=ed.ariesver.online&uuid=73b6dbd5-a27a-4c76-9ad1-42a82380dddb&path=/?ed=2048&format=v2ray
```
```
https://sub.xf.free.hr/api/sub?host=ed.ariesver.online&uuid=73b6dbd5-a27a-4c76-9ad1-42a82380dddb&path=/?ed=2048&format=clash
```
```
https://sub.xf.free.hr/api/sub?host=ed.ariesver.online&uuid=73b6dbd5-a27a-4c76-9ad1-42a82380dddb&path=/?ed=2048&format=singbox
```

**Comment by cmliu** [comment]
订阅转换需要后端，worker顶不住的，弄上去也是需要挂别人的sub来做转换，所以不如直接那这个生成的订阅地址放到在线订阅转换来的方便直接。

**Comment by fscarmen** [comment]
我理解不需要转订阅啊，现在本项目是输入 [YOUR-HOST]、[YOUR-UUID]、[YOUR-PATH]，输出 base64。
现在是把输出base64，多加些输出为 clash , v2ray 等，应该都是套模板的吧

**Comment by fscarmen** [comment]
https://github.com/cmliu/WorkerVless2sub/blob/fa9e92ecf5edbb434c9d76fb88053b8958bac0c6/worker.js#L144C5-L145C1

像这样的链接，都是一个模板，只是这个模板比较短，而clash,sing-box的模板长些，但那是固定好其他内容的，像 inbound / dns / rules 这些，只需要利用自建优选域名拼接输入的字段，生成几个相同 [YOUR-HOST]、[YOUR-UUID]、[YOUR-PATH]，不同优选域名的 proxies / outbound 而已。

**Comment by cmliu** [comment]
现在已经自适应适配clash和sing-box,直接把订阅地址丢进去就行了,不用做转换了
